version: '3.9'

services:

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

    environment:
      - "DJANGO_DEBUG=True"

  db:
    image: postgres:17.0
    ports:
      - "5432:5432"
    env_file:
      - .env

    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"